export const CHANNELS_FULL_UPDATE = 'NEW_CHANNELS_FULL_UPDATE';
export const CHANNEL_PREPENDING_MESSAGES = 'NEW_CHANNEL_PREPENDING_MESSAGES';
export const CHANNEL_PREPEND_MESSAGES = 'NEW_CHANNEL_PREPEND_MESSAGES';
export const CHANNEL_APPENDING_MESSAGES = 'NEW_CHANNEL_APPENDING_MESSAGES';
export const CHANNEL_APPEND_MESSAGES = 'NEW_CHANNEL_APPEND_MESSAGES';

export const CHANNEL_MESSAGE_NEW_REMOTE = 'messages:new';
export const CHANNEL_MESSAGE_NEW_LOCAL = 'NEW_CHANNEL_MESSAGE_NEW_LOCAL';
export const CHANNEL_MESSAGE_UPDATE_ONE = 'NEW_CHANNEL_MESSAGE_UPDATE_ONE';
export const CHANNEL_SET_VISIBLE = 'NEW_CHANNEL_SET_VISIBLE';

export const CHANNELS_SET_LASTSEEN = 'NEW_CHANNELS_SET_LASTSEEN';
export const CHANNELS_SET_VIDEO_SESSION = 'channel:setvideosession';
export const CHANNELS_ADD = 'NEW_CHANNELS_ADD';

export const CHANNELS_REMOTE_ADD = 'channels:newchannel';
